[package]
name = "http"
version = "0.1.0"
description = "A Fluvio connector that fetches data from HTTP endpoints"
edition = "2018"

[dependencies]
tracing = "0.1"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
reqwest = "0.11"
schemars = "0.8"
serde_json = "1"

fluvio-connectors-common = { path = "../../common" }
fluvio-dataplane-protocol = "0.7"
fluvio-future = { version = "0.3.9", features = ["subscriber"] }
