[package]
name = "json-sql"
group = "infinyon"
version = "0.1.0"
apiVersion = "0.1.0"
description = "JSON to SQL transformation Smartmodule"
license = "Apache-2.0"
repository = "https://github.com/infinyon/fluvio"

[[params]]
name = "mapping"
description = "Transformation mapping"
